<template>
  <a  href="#" class="btn btn-primary" id="download" @click="downloadProduct(prepareData(packageJson))" download="package.json"><i class="fas fa-download mr-2"></i>Download</a>
</template>
<script>
  export default {
    name: "filewriter",
    data() {
      return {
        packageJson: {
          name: 'projectName',
          version: '1.0.0',
          description: 'package.json generated by www.settler.dev',
          // main: 'webpack.dev.js',
          dependencies: {
            "autoprefixer": "^8.6.5",
            "base-plugins": "^1.0.0",
            "bootstrap": "^4.3.1",
            "css-loader": "^0.28.11",
            "expose-loader": "^0.7.5"
          },
          devDependencies: {
            "babel-cli": "^6.26.0",
            "babel-core": "^6.26.3",
            "babel-loader": "^7.1.5",
            "babel-plugin-transform-imports": "^1.5.1",
            "babel-preset-env": "^1.7.0",
          },
          // scripts: {
          //  "development": "webpack --config webpack.dev.js",
          //  "production": "webpack --config webpack.prod.js"
          //},
          author: "settler",
          license: "ISC"
        }
      }
    },
    methods: {
      prepareData(packageJson) {
        var $data;
$data = 
`{
  "name": "` + packageJson.name + `",
  "version": "` + packageJson.version + `",
  "description": "` + packageJson.description + `",
  "dependencies": {
    `;

for (var dependency in packageJson.dependencies) {
  var name = Object.keys(dependency);
  $data += `"` + dependency + `": "` + packageJson.dependencies[dependency] + `",
    `;
}

  $data +=
`},
  "dependencies": {
    `;
for (var dependency in packageJson.devDependencies) {
  var name = Object.keys(dependency);
  $data += `"` + dependency + `": "` + packageJson.devDependencies[dependency] + `",
    `;
}
  $data +=
`},
  "author": "` + packageJson.author + `",
  "license": "` + packageJson.license + `"
}`;
        return $data;
      },
      downloadProduct($packageJson) {
        $('#download').attr('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent($packageJson));
      }
    }
  }
</script>