<template>
		<div id='settler-gatherrer'>
      <div class="gatherrer-steps">
        <div class="step-1">
          <adddependency @dependency-submitted="addDependency">
          </adddependency>
    		  <div class="gatherrer-basket">
            <div class="basket-dependency collapseIsActive" :id="dependency.name + 'Dependency'" v-for="dependency in dependencies" :key="dependency.dependencyName">

              <!-- Info -->
              <a class="basket-dependencyName" :href="dependency.links.homepage" target="_blank">{{ dependency.name }}</a>
              <span class="basket-dependencyVersion badge badge-secondary">{{ dependency.version }}</span>
              <a :href="dependency.links.npm" target="_blank"><i class="fab fa-npm"></i></a>
              <a :href="dependency.links.repository" target="_blank"><i class="fab fa-github"></i></a>
              <span class="basket-dependencyDelete" @click="removeDependency(dependency.name)"><i class="fas fa-times"></i></span>
              <span class="basket-dependencyShowAdvanced collapsed" @click="collapseIsActive('#' + dependency.name + 'Advanced')" data-toggle="collapse" :data-target="'#' + dependency.name + 'Advanced'" aria-expanded="false" aria-controls="collapseExample"><i class="fas fa-angle-up"></i></span>

              <!-- Advanced options -->
              <div class="basket-dependencyAdvanced collapse" :id="dependency.name + 'Advanced'">
                <div class="form-group">
                  <input type="checkbox" value="1" v-model="dependency.devDependency">
                  {{ dependency }}
                </div>
                test
              </div>
            </div>
          </div>
          <img v-if="!dependencies[0]" src="/dist/images/no-packages.svg" width="300" height="auto" class="m-auto">
          <div class="gatherrer-stepper">
            <a href="#" class="btn btn-link">Pre-made dependency lists</a>
            <button class="btn btn-primary" @click="nextStep()">Next step</button>
          </div>
        </div>
        <div class="step-2">
          <form>
            <div class="form-row">
              <div class="form-group col-8">
                <label>
                  project name
                </label>
                <input class="form-control" placeholder="AwesomeProject" v-model="packageJSON.name">
              </div>
              <div class="form-group col-4">
                <label>
                  version
                </label>
                <input class="form-control" placeholder="1.0.0" v-model="packageJSON.version">
              </div>
            </div>
            <div class="form-group">
              <label>description</label>
              <textarea class="form-control" rows="2" placeholder="about my awesome project" v-model="packageJSON.description"></textarea>
            </div>
            <div class="form-row">
              <div class="form-group col-8">
                <label>
                  author
                </label>
                <input class="form-control" placeholder="myname" v-model="packageJSON.author">
              </div>
              <div class="form-group col-4">
                <label>
                  liscence
                </label>
                <input class="form-control" placeholder="ISC" v-model="packageJSON.license">
              </div>
            </div>
          </form>
          <div class="gatherrer-stepper">
            <button class="btn btn-primary" @click="nextStep()">Step back</button>
            <filewriter :packageJSON="packageJSON"></filewriter>
          </div>
        </div>
		</div>
  </div>
</template>
<script>
  import adddependency from './add-dependency.vue';
  import filewriter from './file-writer.vue';

  export default {
    name: "settlergatherrer",
    data() {
      return {
        dependencies: [],
        packageJSON: {
          name: 'projectName',
          version: '1.0.0',
          description: 'package.json generated by www.settler.dev',
          // main: 'webpack.dev.js',
          dependencies: {
            "autoprefixer": "^8.6.5",
            "base-plugins": "^1.0.0",
            "bootstrap": "^4.3.1",
            "css-loader": "^0.28.11",
            "expose-loader": "^0.7.5"
          },
          devDependencies: {
            "babel-cli": "^6.26.0",
            "babel-core": "^6.26.3",
            "babel-loader": "^7.1.5",
            "babel-plugin-transform-imports": "^1.5.1",
            "babel-preset-env": "^1.7.0",
          },
          // scripts: {
          //  "development": "webpack --config webpack.dev.js",
          //  "production": "webpack --config webpack.prod.js"
          //},
          author: "settler",
          license: "ISC"
        }
     }
    },
    components: {
      adddependency,
      filewriter
    },
    methods: {
        addDependency(dependency) {
          this.dependencies.push(dependency);
        },
        removeDependency(dependencyName) {
          var removeIndex = this.dependencies.map(function(item){return item.dependencyName;}).indexOf(dependencyName);
          this.dependencies.splice(removeIndex, 1);
        },
        nextStep() {
          $('.step-1').toggleClass('done');
          $('.settler-hills').toggleClass('slide');
        },
        collapseIsActive($dependencyElement) {
          $($dependencyElement).on("show.bs.collapse", function(){
            $($dependencyElement).parent().removeClass('collapseIsActive');
          });
          $($dependencyElement).on("hidden.bs.collapse", function(){
            $($dependencyElement).parent().addClass('collapseIsActive');
          });
        }
    }
  }
  // $('document').ready(function() {
  //   $('.basket-dependencyShowAdvanced').on('click', function() {
  //     $(this).parent().toggleClass('collapseActive');
  //   });
  // });
</script>